services:
  postgres:
    image: postgres:latest
    container_name: pokemon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  adminer:
    image: adminer
    container_name: view
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  postgres_data:
    driver: local
